version: "2"

services:
  qtum:
    container_name: qtum
    build:
      context: .
    image: qtum:latest
    environment:
      - DATA_DIR=/home/qtum/.qtum
    env_file: env
    ports:
    - "3888:3888"
    volumes:
      - data:/home/qtum
    restart: unless-stopped

volumes:
    data:
